---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: downloads-gateway
  namespace: vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: pod-gateway
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.8.1

    # DNS: 172.16.1.1

    addons:
      vpn:
        enabled: true
        type: gluetun
        image:
          repository: docker.io/qmcgaw/gluetun
          tag: latest #v3.32.0
        env:
          - name: VPN_SERVICE_PROVIDER
            value: mullvad
          - name: VPN_TYPE
            value: wireguard
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off"
          - name: WIREGUARD_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: gateway-vpnconfig
                key: WIREGUARD_PRIVATE_KEY
          - name: WIREGUARD_ADDRESSES
            valueFrom:
              secretKeyRef:
                name: gateway-vpnconfig
                key: WIREGUARD_ADDRESSES
          # - name: VPN_TYPE
          #   value: openvpn
          # - name: OPENVPN_USER
          #   valueFrom:
          #     secretKeyRef:
          #       name: gateway-vpnconfig
          #       key: OPENVPN_USER
        securityContext:
          capabilities:
            add:
              - NET_ADMIN

      # netshoot:
      #   enabled: true

    livenessProbe:
      exec:
        command:
          - sh
          - -c
          - if [ $(wget -q -O- https://ipinfo.io/country) == 'AT' ]; then exit 0; else exit $?; fi
      initialDelaySeconds: 30
      periodSeconds: 60
      failureThreshold: 3

    # publicPorts:
    #   - IP: 10
    #     hostname: qbittorrent
    #     ports:
    #       - port: 56202
    #         type: udp
    #       - port: 56202
    #         type: tcp

    networkPolicy:
      enabled: true

      egress:
        - to:
          - ipBlock:
              cidr: 0.0.0.0/0
          ports:
          # VPN traffic
          - port: &vpn_port 1637
            protocol: UDP
        - to:
          - ipBlock:
              cidr: 10.0.0.0/8

    routed_namespaces:
      - mediaserver

    settings:
      # NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_BLOCK_OTHER_TRAFFIC: true
      # VPN_INTERFACE: wg0
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_TRAFFIC_PORT: *vpn_port
      # VXLAN_ID: 1
      # VXLAN_IP_NETWORK: 172.16.1
      IPTABLES_NFT: yes

    webhook:
      gatewayAnnotation: setGateway
      gatewayDefault: false
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.7.0
