apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &release radarr
spec:
  releaseName: *release
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 5.5.1.8747@sha256:4ae36e5329fa90aa95e180a9abad4856e147500f65cf7262a193f08a2480a136

    env:
      TZ: Europe/Vienna
      RADARR__INSTANCE_NAME: Radarr
      RADARR__PORT: &port 7878
      RADARR__APPLICATION_URL: &host "radarr.${SECRET_DOMAIN}"
      RADARR__LOG_LEVEL: info
      # RADARR__API_KEY:
      #   valueFrom:
      #     secretKeyRef:
      #       name: radarr-secrets
      #       key: api_key

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: radarr-tls

    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
        mountPath: /config
      media:
        enabled: true
        existingClaim: media
        path: /media
        mountPath: /data/media