apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &release radarr
spec:
  releaseName: *release
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/radarr
              tag: 5.28.0
            env:
              TZ: Europe/Vienna
              RADARR__INSTANCE_NAME: Radarr
              RADARR__PORT: &port 7878
              RADARR__APPLICATION_URL: &host "radarr.${SECRET_DOMAIN}"
              RADARR__LOG_LEVEL: info

    service:
      main:
        controller: main
        ports:
          http:
            port: *port

    route:
      main:
        hostnames:
          - *host
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        existingClaim: radarr-config
        globalMounts:
          - path: /config
      downloads:
        existingClaim: lp-downloads
        globalMounts:
          - path: /data/media/downloads
      movies:
        existingClaim: pvc-movies
        globalMounts:
          - path: /data/media/movies