apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &release radarr
spec:
  releaseName: *release
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/radarr
              tag: 5.17.2
            env:
              TZ: Europe/Vienna
              RADARR__INSTANCE_NAME: Radarr
              RADARR__PORT: &port 7878
              RADARR__APPLICATION_URL: &host "radarr.${SECRET_DOMAIN}"
              RADARR__LOG_LEVEL: info

    service:
      main:
        controller: main
        ports:
          http:
            port: *port

    ingress:
      main:
        className: "nginx"
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: main
                  port: http

    persistence:
      config:
        existingClaim: radarr-config
        globalMounts:
          - path: /config
      media:
        existingClaim: media
        globalMounts:
          - path: /data/media