---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zfs-scrub
spec:
  chartRef:
    kind: OCIRepository
    name: zfs-scrub
  interval: 30m
  values:
    controllers:
      zfs-scrub:
        type: cronjob
        cronjob:
          schedule: "0 1 * * 0"
          concurrencyPolicy: Forbid
        containers:
          app:
            image:
              # docker.io/openebs/zfs-driver is already deployed by openebs and includes zpool
              repository: docker.io/openebs/zfs-driver
              tag: 2.9.0
            command:
              - "/scripts/zfs_scrub_task.sh"
            env:
              ZPOOL: zfspv-pool
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
    persistence:
      scripts:
        type: configMap
        name: zfs-scrub-scripts
        defaultMode: 0755
        globalMounts:
          - path: /scripts
      dev:
        type: hostPath
        hostPath: /dev
        hostPathType: Directory
        globalMounts:
          - path: /dev
