---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Vienna
  METALLB_LB_RANGE:  192.168.10.220-192.168.10.230
  METALLB_K8S_GATEWAY_ADDR:  192.168.10.220
  METALLB_INGRESS_ADDR: 192.168.10.221