---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: system
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.12.1
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
      interval: 30m
  values:
    controller:
      runOnControlPlane: true