---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: system
spec:
  chartRef:
    kind: OCIRepository
    name: csi-driver-nfs
  interval: 30m
  values:
    controller:
      runOnControlPlane: true