---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: system
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-smb
      version: v1.18.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-csi
        namespace: flux-system
      interval: 30m
  values:
    controller:
      runOnControlPlane: true