---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  maxHistory: 2
  timeout: 20m
  chart:
    spec:
      chart: grafana
      version: 6.52.4
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:





    ingress:
      enabled: true
      ingressClassName: nginx
      pathType: Prefix
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - &host_grafana "grafana.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host_grafana
          secretName: grafana-tls