---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-reloader
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/system/reloader/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true