---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: network
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 1.15.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        value: "${SECRET_CLOUDFLARE_TOKEN}"
    policy: sync
    txtOwnerId: default
    txtPrefix: k8s.
    domainFilters: ["${SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true