---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: network
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 1.14.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    provider: cloudflare
    env:
      - name: CF_API_EMAIL
        value: "${SECRET_CLOUDFLARE_EMAIL}"
      - name: CF_API_KEY
        value: "${SECRET_CLOUDFLARE_KEY}"
    extraArgs:
      - --ingress-class=external
      - --cloudflare-proxied
    policy: sync
    txtOwnerId: default
    txtPrefix: k8s.
    domainFilters: ["${SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true