---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-backups
  namespace: system
spec:
  volumeName: pv-backups
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
