---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  maxHistory: 2
  timeout: 20m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 59.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    alertmanager:
      ingress:
        enabled: true
        ingressClassName: nginx
        pathType: Prefix
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - &host_alertmanager "alertmanager.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host_alertmanager
            secretName: alertmanager-tls

    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        pathType: Prefix
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - &host_grafana "grafana.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host_grafana
            secretName: grafana-tls

    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        pathType: Prefix
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - &host_prometheus "prometheus.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host_prometheus
            secretName: prometheus-tls
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false