apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: conbee-gateway
spec:
  brokerProperties: {}
  capacity: 1
  discoveryHandler:
    name: udev
    discoveryDetails: |
      groupRecursive: true
      udevRules:
      - SUBSYSTEM=="tty", ATTR{product}=="ConBee II"