apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: zigbee-gateway
spec:
  brokerProperties: {}
  capacity: 1
  discoveryHandler:
    name: udev
    discoveryDetails: |
      groupRecursive: true
      udevRules:
      - ENV{ID_SERIAL}=="Sonoff", SUBSYSTEM=="tty"