apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: zigbee-gateway
spec:
  brokerProperties: {}
  capacity: 1
  discoveryHandler:
    name: udev
    discoveryDetails: |
      groupRecursive: true
      udevRules:
      - ENV{ID_SERIAL}=="Sonoff Zigbee 3.0 USB Dongle Plus", SUBSYSTEM=="tty"