apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - prowlarr/ks.yaml
  - sonarr/ks.yaml
  - radarr/ks.yaml
  # - readarr/ks.yaml
  - jellyfin/ks.yaml
  - sabnzbd/ks.yaml
  # - calibre/ks.yaml