apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lp-downloads
  namespace: media
  labels:
    app.kubernetes.io/name: config
    app.kubernetes.io/instance: downloads
    app.kubernetes.io/managed-by: local-path-provisioner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi