apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-movies
  namespace: media
  labels:
    app.kubernetes.io/name: data
    app.kubernetes.io/instance: movies
spec:
  volumeName: pv-movies
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi