apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shows
  namespace: media
  labels:
    app.kubernetes.io/name: data
    app.kubernetes.io/instance: shows
spec:
  volumeName: pv-shows
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi