---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &release kavita
spec:
  releaseName: *release
  chartRef:
    kind: OCIRepository
    name: kavita
  interval: 30m
  values:
    controllers:
      kavita:
        containers:
          app:
            image:
              repository: ghcr.io/kareadita/kavita
              tag: 0.9.0.2
            env:
              TZ: Europe/Vienna
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    service:
      app:
        controller: kavita
        ports:
          http:
            port: &port 5000

    persistence:
      config:
        existingClaim: *release
        advancedMounts:
          kavita:
            app:
              - path: /kavita/config
      books:
        existingClaim: pvc-books
        advancedMounts:
          kavita:
            app:
              - path: /books

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Kavita"
          gethomepage.dev/group: "Self-Hosted"
          gethomepage.dev/weight: "30"
          gethomepage.dev/icon: "kavita"
          gethomepage.dev/href: "https://books.muellner.dev"
          gethomepage.dev/app: "kavita"
          gethomepage.dev/widget.type: "kavita"
          gethomepage.dev/widget.url: "http://kavita.selfhosted:5000"
          gethomepage.dev/widget.username: '{{ "{{HOMEPAGE_VAR_KAVITA_USERNAME}}" }}'
          gethomepage.dev/widget.password: '{{ "{{HOMEPAGE_VAR_KAVITA_PASSWORD}}" }}'
        hostnames:
          - books.muellner.dev
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
