---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-books
  namespace: selfhosted
spec:
  volumeName: pv-books
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
