---
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: weekly
spec:
  enabled: true
  trigger:
    schedule: 0 2 * * *
  repository:
    repository: volsync-maintenance-secret
