---
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:sXcul+Yd7tOlnDFEr4gZj8aB4xKdDJiY,iv:tzBg7LwS4uWtvbt6i/JisfdupTr0exl2GujVRABz66w=,tag:RKvrqnrSh4cs84G/UPR2Fw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:2yDRRhP+duEPSj16BThalN453lBkiOYfZHamar9KS/IxFhDgAVpS2mKUsoSIN8RvXwuzzairUBR8dkMmqayhow==,iv:X62cOh0zf/Pi72EtIkZlbnko+tb4bXKFN1iqOiC4V1c=,tag:azXDHOCxnZ8mOkNDUqP5SQ==,type:str]
sops:
  age:
    - recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtL0I5NU14ZWpzOW5GVit1
        OXpJQ3lHSXhzTVlHUzlEa2tLVGgybWhtZG40CjFnbGFvVkFGeHoydXcxcFdGeUs3
        cGlVTXYvQXAwN2ppQmJSKytERDhzbVkKLS0tICtmVHdyRytKcU8vbGtCeTIvbnpD
        d3RyTUFad1p2OXN4SmE0Tk55OXV1N2sK760N/YQ3FR4egqX631/sMjIQRo4c3eQd
        sUhGL0S1tPjbbCEmd+G4IsxU8URTF5zGQEa8RIUwr/AKTKCcvNkJdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T13:47:37Z"
  mac: ENC[AES256_GCM,data:3lOzgLhVgJ+gVLf7edPldK17yoqi6U+jvwfnW72uC9noZcJIgW5li7PzExYWI3nlJ5XW7uooF136Fq+mOSJGLwfFY6nfVIk/GW40N5lu3FTTkx0Ww+dR+r5HIWNAa2PcGocTdT1fozz2AGqiui7YZ9bp2xbSDruiCB3Ylt5bA1g=,iv:kv41DX0/2TUWYQW5B68FhWy78e5PPsTXEnq/qy3GP9M=,tag:nUPR02Ue9aL7E/Mg1JppzA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
