---
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:H90kL3SQI4osm1aF07B5xDuMRXvDf6u/KQPPfg==,iv:jwfned5z3vC+lPYlWHwGpVwH1yv5KNSGOFxcNET2UOQ=,tag:I2tAB27dXCdOl9n3iBaFnQ==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:aSO+MsMrKv00abN6viog3hae+9JdRg6IqBvMAwRpzFK7gz+ISkvqBnsngYv3QKF6/kef+5YGhN1TrAfzYWw7HA==,iv:YhddATYeeB/jPPxXnslhc61XutwsI3Gc9e7sK+eag74=,tag:X4/6FnZZzSKCecdAQuj4WQ==,type:str]
sops:
  age:
    - recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWlBTcFZpTmx0a2QyZHc4
        bzZtb1JzSkZHYVNVTUFvY2FRN1ZKOGdiQndzCnpPWnBoY0l1b2NZamFrUittak4z
        SVNzZExmRmc1TEpHVlNKZ09mT3RBSTAKLS0tICt6QW5WcXE2VDRWTDZQeG5uRFpu
        SUNjVjR1NmRDZjJqc0poTXgwVjJlRlkKN3GGkm1lfcnZGnUokCUZGajB2eShhphI
        1/wy651hbOb55zBQKGRKZB0JB23L5VAlfPPxfkKgcEhRoJGoW/r4ig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T14:34:34Z"
  mac: ENC[AES256_GCM,data:Jqxg8byoOxZ7phWjeRcJGxHB5IpWX9XIt34Lr6Rz4gu+7RRqvZwVRRyAzwGZv8MiMLx52v8DVODqqTvTTXsfrk3N9frFz2gfbd4IqEGHL5f1as8lhi//qUJPAVcpCR0/qe18xiqqzLIhXLlC4npLBV3n7P63OiqU7aq+YevbXlQ=,iv:zQFrN9Vp7BFDXps4vGZKRNu4/0tbf2PEzsbo+CHT6Ms=,tag:YMZijz5o6w9IxkqGF9hAtw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
