machine:
  install:
    wipe: true
  nodeLabels:
    $patch: delete
    openebs.io/engine: "mayastor"
  sysctls:
    vm.nr_hugepages: "1024"
  kubelet:
    extraMounts:
      - destination: /var/local
        type: bind
        source: /var/mnt/local-storage
        options:
          - bind
          - rshared
          - rw
cluster:
  network:
    cni:
      name: none
  proxy:
    disabled: true
  apiServer:
    certSANs:
    - cluster.local
    extraArgs:
      feature-gates: MutatingAdmissionPolicy=true
      runtime-config: admissionregistration.k8s.io/v1beta1=true
  allowSchedulingOnControlPlanes: true
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: system_disk
  minSize: 600GB
  maxSize: 600GB
  grow: false
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-storage
provisioning:
  diskSelector:
    match: system_disk
  minSize: 200GB
  maxSize: 300GB