machine:
  install:
    image: factory.talos.dev/metal-installer/4dd8e3a8b6203d3c14f049da8db4d3bb0d6d3e70c5e89dfcc1e709e81914f63c:v1.12.3
    wipe: true
  kernel:
    modules:
      - name: zfs
  nodeLabels:
    $patch: delete
cluster:
  network:
    cni:
      name: none
  proxy:
    disabled: true
  apiServer:
    certSANs:
    - cluster.local
    extraArgs:
      feature-gates: MutatingAdmissionPolicy=true
      runtime-config: admissionregistration.k8s.io/v1beta1=true
  allowSchedulingOnControlPlanes: true
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: system_disk
  minSize: 250GB
  maxSize: 300GB
  grow: false
---
apiVersion: v1alpha1
kind: RawVolumeConfig
name: openebs-zfs
provisioning:
  diskSelector:
    match: system_disk
  minSize: 500GB
  maxSize: 800GB