apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediaserver
resources:
  - helmrelease.yaml
  - pvc.yaml
commonLabels:
  app.kubernetes.io/name: sonarr
  app.kubernetes.io/instance: sonarr