---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-credentials
  namespace: home-automation
stringData:
  MQTT_USERNAME: ENC[AES256_GCM,data:oXETKA==,iv:V7Q9hDzqVAJrWu+ssuPaljJgDEmwOh8OOklPzRa4Q20=,tag:st+a6yxdazta5IeSEM/Fmw==,type:str]
  MQTT_PASSWORD: ENC[AES256_GCM,data:zb0LYLl/kTotKXk6NR6+GpXmH2uY0CjLmfD3gjaGso4=,iv:UERfEEMMOH5a6YEmpRMN2h41hbLXX2CwbzkWWY6+Mq0=,tag:X8crBmF7Lg4gzDPdoy46Vw==,type:str]
sops:
  age:
    - recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdCtSdmh6UldYaVBaQnhk
        by9XVDJ2czZDWE1ueFRQT01Dc1pOVkZwbzM4Ckd5OVVRaFFUY0ZrTnJsZDBMZ1hP
        N3BBeHBHNlRWNnU2dnR2RlVDU2NHQncKLS0tIGMzUXhYUGNBQ25nMXJiOTJNbjNQ
        a05zUmVGeDVINWNzWEhERlRuczlOOGsKOHidkMGKU/QySg1tmKQPYMykKDpRMaSy
        KjmvD4atoSQ8OyHlJ0ZK+J7YYDeXZd3fsM8u/ATqh4JC2Ocs5Vc6Kg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T15:15:30Z"
  mac: ENC[AES256_GCM,data:a/hlZ5U6+E/dr38Cc64/H9rZchagFjBnD+vjc62Fd6WkxA5afaMlCFOFQwi4NRfRYFxRpBWVnp5mW9FJKhFHsBu0yr4jqT8mdmpcxYXmIUNJM88waUtdmHT5BKXHFaaqmwGTb4A5nqC++KlQRAJxDcLeXVfcB1RM0mJjvJxLswY=,iv:cD1yGNrv6e94egUAyc3aFigbh87tIhpqVWe1XbKjWC8=,tag:dOQ4hWZi/Zlum+VMY7Ulkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
