---
- trigger:
    - trigger: state
      entity_id: weather.forecast_home
    - trigger: time_pattern
      hours: "/1"
  action:
    - action: weather.get_forecasts
      target:
        entity_id: weather.forecast_home
      data:
        type: daily
      response_variable: forecast_data
  sensor:
    - name: "Weather Forecast Day 0 High"
      unique_id: weather_forecast_day_0_high
      default_entity_id: sensor.weather_forecast_day_0_high
      unit_of_measurement: "°C"
      state: '{{ forecast_data["weather.forecast_home"].forecast[0].temperature | default("N/A") }}'
    - name: "Weather Forecast Day 0 Low"
      unique_id: weather_forecast_day_0_low
      default_entity_id: sensor.weather_forecast_day_0_low
      unit_of_measurement: "°C"
      state: '{{ forecast_data["weather.forecast_home"].forecast[0].templow | default("N/A") }}'
    - name: "Weather Forecast Day 0 Condition"
      unique_id: weather_forecast_day_0_condition
      default_entity_id: sensor.weather_forecast_day_0_condition
      state: '{{ forecast_data["weather.forecast_home"].forecast[0].condition | default("unknown") }}'
    - name: "Weather Forecast Day 1 High"
      unique_id: weather_forecast_day_1_high
      default_entity_id: sensor.weather_forecast_day_1_high
      unit_of_measurement: "°C"
      state: '{{ forecast_data["weather.forecast_home"].forecast[1].temperature | default("N/A") }}'
    - name: "Weather Forecast Day 1 Low"
      unique_id: weather_forecast_day_1_low
      default_entity_id: sensor.weather_forecast_day_1_low
      unit_of_measurement: "°C"
      state: '{{ forecast_data["weather.forecast_home"].forecast[1].templow | default("N/A") }}'
    - name: "Weather Forecast Day 1 Condition"
      unique_id: weather_forecast_day_1_condition
      default_entity_id: sensor.weather_forecast_day_1_condition
      state: '{{ forecast_data["weather.forecast_home"].forecast[1].condition | default("unknown") }}'
    - name: "Weather Forecast Day 2 High"
      unique_id: weather_forecast_day_2_high
      default_entity_id: sensor.weather_forecast_day_2_high
      unit_of_measurement: "°C"
      state: '{{ forecast_data["weather.forecast_home"].forecast[2].temperature | default("N/A") }}'
    - name: "Weather Forecast Day 2 Low"
      unique_id: weather_forecast_day_2_low
      default_entity_id: sensor.weather_forecast_day_2_low
      unit_of_measurement: "°C"
      state: '{{ forecast_data["weather.forecast_home"].forecast[2].templow | default("N/A") }}'
    - name: "Weather Forecast Day 2 Condition"
      unique_id: weather_forecast_day_2_condition
      default_entity_id: sensor.weather_forecast_day_2_condition
      state: '{{ forecast_data["weather.forecast_home"].forecast[2].condition | default("unknown") }}'
    - name: "Weather Forecast Day 3 High"
      unique_id: weather_forecast_day_3_high
      default_entity_id: sensor.weather_forecast_day_3_high
      unit_of_measurement: "°C"
      state: '{{ forecast_data["weather.forecast_home"].forecast[3].temperature | default("N/A") }}'
    - name: "Weather Forecast Day 3 Low"
      unique_id: weather_forecast_day_3_low
      default_entity_id: sensor.weather_forecast_day_3_low
      unit_of_measurement: "°C"
      state: '{{ forecast_data["weather.forecast_home"].forecast[3].templow | default("N/A") }}'
    - name: "Weather Forecast Day 3 Condition"
      unique_id: weather_forecast_day_3_condition
      default_entity_id: sensor.weather_forecast_day_3_condition
      state: '{{ forecast_data["weather.forecast_home"].forecast[3].condition | default("unknown") }}'
- trigger:
    - trigger: time_pattern
      minutes: "/15"
  action:
    - action: calendar.get_events
      target:
        entity_id:
          - calendar.shared
      data:
        duration:
          days: 14
      response_variable: calendar_events
    - action: python_script.esp_calendar_data_conversion
      data:
        calendar: "{{ calendar_events }}"
        now: "{{ now().isoformat().split('T')[0] }}"
        nr_entries: 8
        prefix_length: 3
        prefix_separator: ": "
      response_variable: output
  sensor:
    - name: ESP Calendar Data
      unique_id: esp_calendar_data
      state: "OK"
      attributes:
        entries: "{{ output.entries }}"
        closest_end_time: "{{ output.closest_end_time }}"
