# Define the files which contains the configs. As k8s config maps
# Are read only by design, we need to extract dynamic config to external files
devices: devices.yaml
groups: groups.yaml
homeassistant:
  discovery_topic: homeassistant
  enabled: true
  legacy_entity_attributes: true
  legacy_triggers: false
  status_topic: hass/status
ota:
  disable_automatic_update_check: false
  ikea_ota_use_test_url: false
  update_check_interval: 1440
permit_join: false
blocklist: []
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
mqtt:
  server: mqtt://localhost:1883
serial:
  baudrate: 115200
  disable_led: false
  port: /dev/ttyUSB0
  rtscts: false
frontend:
  auth_token: null
  host: 0.0.0.0
  port: 8080
  url: null
advanced:
  adapter_concurrent: null
  adapter_delay: 0
  cache_state: true
  cache_state_persistent: true
  cache_state_send_on_startup: true
  channel: 11
  elapsed: false
  last_seen: disable
  legacy_api: false
  log_level: info
  log_output:
  - console
  report: true
  timestamp_format: YYYY-MM-DD HH:mm:ss
  transmit_power: 5
