---
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:2SyT21uHVpvn0RZCkf1pzGM1tbesJzBcd2CCsQ==,iv:AXwFPEQwShAUVNczLfiq2Ysc1CBA8+/e3epz2VySFMM=,tag:EBMFRFCQU2yBiJkrjbQ1Lw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:ZbEPFzYizcVDnB6Gridq41D4E8mZUAxATrZXmr2IyId/A38ayF0Z5PwfiVUQ4eDxkxKRJYNh4DwXnpPzK/TriA==,iv:QViDWXruRXzc31AftkUjdl9t94KJphKRkmn5+PG1IS0=,tag:EI8yghq+w8R5YBUc1rUREA==,type:str]
sops:
  age:
    - recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQ2F6ZWl4UWVWaXZtUktB
        djdjZlcxSGJjVDBYdUNGck5ySlJTV1Fnc0M0ClNxYmdUTTk0eS9zVVNBZGJoK0FG
        SXoxUEdXS1dNbHJCU1JaMzBnaFlZcTAKLS0tIFZHL1ZmUGJYOVBQbG1QTS8vaTRO
        K1UwT1pNNzlzTFd2cXBmc3hITmNQT3cKrSw3xOuShENPh5j3slMQg0oNa7U0I/7+
        2ti9kbOcZUUjVfcdvXRE3kVDe2QVXBVwEee3f880vX6TrNHJPNV6Wg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T14:33:41Z"
  mac: ENC[AES256_GCM,data:9nLCx5oiKe0jUW2Jp/CR8Xw7AXrkuCoTJT7iMdB0LLUS5TUlRcTwjdXrxYXKTTdiwnhJD5XKMHD7VdADuxouBd/Fz0FimIB6A6in6b7AF66H8OieOwaSgSY3Asgg5njf+sL6W5bhjGHytXhxANKrRE+q8BGMcdyZNIm363vWiuI=,iv:yIoUkMbSk2C33+fj9HCSlsl0wJGaDVNd4nzF68Kk+c8=,tag:jCdiQ1rbxtOyTYuK60alew==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
