---
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:FkiFAzQkd9fXSD1OxZ9ba+86DXprqx5w,iv:5HGfnHJnBDy2pdJ0sypcD+kr8CRKSr49prFi4JiIOKs=,tag:i+7wWUHfZxZ90Xo/lL/qqw==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:5Dh6AjjUx/uPRBf4FBkv1k8POFoQJdXWjcsULPL1GzvrIbFY7644VAmJdDMINP/ZFIMFNW+jsob7cXwYa+Y7/w==,iv:Uxw0Oe2IuZYENHSal4STuI/UsyMwUxtPt+HiLVRjtb4=,tag:7hNxoaMmdzsy5ph8oj9zzA==,type:str]
sops:
  age:
    - recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSjN5NG5UTVhmaWtNMFFr
        a0pEY241aERJaWFiTHRWY2duOVJ3RFlFRG1JCitzOU5Id0ZyN3RSNFZkUlR2cDMv
        Ry91ZGdZYXZoRGgvRWZublNsT3Y4aUkKLS0tIGtEd3hUVlVlOWZHMnFLV3JFeUhr
        WHE4L1FZa3ZlTnkyRjhMYVJMSzZUL1kK76HETIsJJRqPbuspyVlAqK/FwT5zr2z3
        DUlC2qePy87PwOotKS/i6v3IvlPcNKBI0iamtusPMTnMy5azIBUHwA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T13:47:05Z"
  mac: ENC[AES256_GCM,data:Rb3qFDQfXVA0AFsTNUSlknYlSCEmOLezE6oXD0x4lJKFhWPr/8yRFzSFTpXhb1oLfIvsoU01iPPHDaHphxadhO+991/FpeBgGR8HFYMTZHq3/sQtMdhGJk443xI8BlOjudVigmRs/OunTGoN8gJSa9MvfbEK+E8vU6Al9u+LByM=,iv:O1fDeGnDOlCTOFoDiDI+EloU89/8uqIt/OCTbY3mT1k=,tag:bVTD0XCeFajy/sT/otwjpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
