---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ./apitoken-secret.yaml
  - ./issuer-letsencrypt-staging.yaml
  - ./issuer-letsencrypt-production.yaml
