apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &release readarr
spec:
  releaseName: *release
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      readarr:
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/readarr
              tag: 0.4.18-develop
            env:
              TZ: Europe/Vienna
              READARR__INSTANCE_NAME: Readarr
              READARR__PORT: &port 8787
              READARR__APPLICATION_URL: &host "readarr.${SECRET_DOMAIN}"
              READARR__LOG_LEVEL: info

    service:
      app:
        controller: readarr
        ports:
          http:
            port: *port

    ingress:
      app:
        className: "nginx"
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: readarr-config
        globalMounts:
          - path: /config
      media:
        existingClaim: media
        globalMounts: 
          - path: /data/media