---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
spec:
  chartRef:
    kind: OCIRepository
    name: homeassistant
  interval: 30m
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2026.10.0@sha256:1b64d38f38d922bf9d59336451fd6453e1d614f934456af4ee3d2a51061be3a4

    service:
      main:
        ports:
          http:
            port: 8123

    route:
      main:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Home Assistant"
          gethomepage.dev/group: "Home Automation"
          gethomepage.dev/icon: "home-assistant"
          gethomepage.dev/href: "https://home.muellner.dev"
          gethomepage.dev/app: "homeassistant"
          gethomepage.dev/widget.type: "homeassistant"
          gethomepage.dev/widget.url: "http://homeassistant.home-automation:8123"
          gethomepage.dev/widget.key: '{{ "{{HOMEPAGE_VAR_HOMEASSISTANT_KEY}}" }}'
        hostnames:
          - "home.muellner.dev"
        parentRefs:
          - name: envoy-external
            namespace: network

    persistence:
      configuration-file:
        type: configMap
        name: homeassistant-config
        globalMounts:
          - path: /config/configuration.yaml
            subPath: configuration.yaml
      config:
        existingClaim: homeassistant-config
        globalMounts:
          - path: /config
      binary-sensor-file:
        type: configMap
        name: homeassistant-binary-sensor
        globalMounts:
          - path: /config/binary_sensor.yaml
            subPath: binary_sensor.yaml
      sensor-file:
        type: configMap
        name: homeassistant-sensor
        globalMounts:
          - path: /config/sensor.yaml
            subPath: sensor.yaml
      template-file:
        type: configMap
        name: homeassistant-template
        globalMounts:
          - path: /config/template.yaml
            subPath: template.yaml
