---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
spec:
  chartRef:
    kind: OCIRepository
    name: homeassistant
  interval: 30m
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2026.4.3@sha256:ae0800c81fea16bc1241ce03bddb9c6260566e90f58b09d3e5a629e4f68bdc0b

    service:
      main:
        ports:
          http:
            port: 8123

    route:
      main:
        hostnames:
          - "home.muellner.dev"
        parentRefs:
          - name: envoy-external
            namespace: network

    persistence:
      configuration-file:
        type: configMap
        name: homeassistant-config
        globalMounts:
          - path: /config/configuration.yaml
            subPath: configuration.yaml
      config:
        existingClaim: homeassistant-config
        globalMounts:
          - path: /config
      binary-sensor-file:
        type: configMap
        name: homeassistant-binary-sensor
        globalMounts:
          - path: /config/binary_sensor.yaml
            subPath: binary_sensor.yaml
      sensor-file:
        type: configMap
        name: homeassistant-sensor
        globalMounts:
          - path: /config/sensor.yaml
            subPath: sensor.yaml
      template-file:
        type: configMap
        name: homeassistant-template
        globalMounts:
          - path: /config/template.yaml
            subPath: template.yaml
