---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: pv-shows
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "shows"
    volumeAttributes:
      server: "192.168.1.200"
      share: "/volume/04ba54d5-e293-41bf-92ab-4be09c2a4331/.srv/.unifi-drive/shows/.data"
  mountOptions:
    - nolock
    - nfsvers=3
