apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &release prowlarr
spec:
  releaseName: *release
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/prowlarr-develop
      tag: 1.17.1.4483@sha256:0a673d1e699c5cf4f4f956d85c4f3cb2b0ecbf13b087d02a4e2fe87a307d7c3f

    env:
      TZ: Europe/Vienna
      PROWLARR__INSTANCE_NAME: Prowlarr
      PROWLARR__PORT: &port 9696
      PROWLARR__LOG_LEVEL: info
      PROWLARR__ANALYTICS_ENABLED: "False"
      # PROWLARR__API_KEY:
      #   valueFrom:
      #     secretKeyRef:
      #       name: prowlarr-secrets
      #       key: api_key

    hostname: prowlarr

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "prowlarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: prowlarr-tls

    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config
        mountPath: /config
