apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &release prowlarr
spec:
  releaseName: *release
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/prowlarr
              tag: 2.1.5
            env:
              TZ: Europe/Vienna
              PROWLARR__INSTANCE_NAME: Prowlarr
              PROWLARR__PORT: &port 9696
              PROWLARR__LOG_LEVEL: info
              PROWLARR__ANALYTICS_ENABLED: "False"

    service:
      main:
        controller: main
        ports:
          http:
            port: *port

    route:
      main:
        hostnames:
          - "prowlarr.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        existingClaim: prowlarr-config
        globalMounts:
        - path: /config
