---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./secret.sops.yaml
  - ./configmap.yaml
  - ./pvc-photos.yaml
  - ./pvc-ml.yaml
  - ./pvc-photos-backup.yaml
  - ./volsync-photos-secret.sops.yaml
  - ./configmap-kopia-policy.yaml
  - ./replicationsource-photos.yaml
  - ./kopiamaintenance-photos.yaml
