---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./secret.sops.yaml
  - ./configmap.yaml
  - ./pvc-photos.yaml
  - ./pvc-ml.yaml

patches:
  - patch: |
      - op: add
        path: /spec/kopia/sourceIdentity/sourceNamespace
        value: media
    target:
      kind: ReplicationDestination
