---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-photos-backup
  labels:
    app.kubernetes.io/name: data
    app.kubernetes.io/instance: photos-backup
spec:
  volumeName: pv-photos-backup
  storageClassName: nfs-csi
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
