apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &release jellyseerr
spec:
  releaseName: *release
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/fallenbagel/jellyseerr
              tag: 2.7.3

    service:
      main:
        controller: main
        ports:
          http:
            port: 5055

    ingress:
      main:
        className: nginx
        hosts:
          - host: &host "jellyseerr.${SECRET_DOMAIN}"
            paths:
            - path: /
              service:
                identifier: main
                port: http

    persistence:
      config:
        existingClaim: jellyseerr-config
        globalMounts:
        - path: /app/config