apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &release jellyseerr
spec:
  releaseName: *release
  chartRef:
    kind: OCIRepository
    name: jellyseerr
  interval: 30m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/fallenbagel/jellyseerr
              tag: 2.7.3

    service:
      main:
        ports:
          http:
            port: 5055

    route:
      main:
        hostnames:
          - "jellyseerr.muellner.dev"
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        existingClaim: jellyseerr-config
        globalMounts:
        - path: /app/config