apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &release jellyseerr
spec:
  releaseName: *release
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/fallenbagel/jellyseerr
              tag: 2.7.3

    service:
      main:
        ports:
          http:
            port: 5055

    route:
      main:
        hostnames:
          - "jellyseerr.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        existingClaim: jellyseerr-config
        globalMounts:
        - path: /app/config