---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-operator
spec:
  interval: 1h
  path: ./apps/flux-system/flux-operator/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-ops
  targetNamespace: flux-system
  timeout: 5m
  wait: false
