apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &release jellyfin
spec:
  releaseName: *release
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: docker.io/jellyfin/jellyfin
      tag: 10.9.3@sha256:3022b48f18c810fe7a6a77ba3aef05bdbc9a05f253e856d2c96916fcdbcfc0f6

    service:
      main:
        ports:
          http:
            port: 8096

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: jellyfin-tls

    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
        mountPath: /config
      media:
        enabled: true
        existingClaim: media
        path: /media
        mountPath: /data/media