apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &release jellyfin
spec:
  releaseName: *release
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/jellyfin/jellyfin
              tag: 10.10.7

    service:
      main:
        controller: main
        ports:
          http:
            port: 8096

    ingress:
      main:
        className: nginx
        hosts:
          - host: &host "jellyfin.${SECRET_DOMAIN}"
            paths:
            - path: /
              service:
                identifier: main
                port: http

    persistence:
      config:
        existingClaim: jellyfin-config
        globalMounts:
        - path: /config
      shows:
        existingClaim: smb-shows
        globalMounts:
        - path: /data/media/shows
      movies:
        existingClaim: smb-movies
        globalMounts:
        - path: /data/media/movies