apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &release jellyfin
spec:
  releaseName: *release
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/jellyfin
      tag: 10.8.8

    service:
      main:
        ports:
          http:
            port: 8096

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
        mountPath: /config
      media:
        enabled: true
        existingClaim: media
        path: /media
        mountPath: /data/media