apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &release jellyfin
spec:
  releaseName: *release
  chartRef:
    kind: OCIRepository
    name: jellyfin
  interval: 30m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/jellyfin/jellyfin
              tag: 10.11.2

    service:
      main:
        ports:
          http:
            port: 8096
    
    route:
      main:
        hostnames:
          - "jellyfin.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        existingClaim: jellyfin-config
        globalMounts:
        - path: /config
      shows:
        existingClaim: pvc-shows
        globalMounts:
        - path: /data/media/shows
      movies:
        existingClaim: pvc-movies
        globalMounts:
        - path: /data/media/movies