---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.5.5@sha256:f4a1a5eece13beed61e579172d2a54b1fc2e7ff2bbdbd7ef22a4d9f6fc36e198

    podAnnotations:
      setGateway: "true"

    env:
      UMASK: "022"
      QBITTORRENT__PORT: &port 8080
      QBITTORRENT__USE_PROFILE: "true"
      QBT_BitTorrent__Session__DefaultSavePath: "/data/media/Downloads"

    hostname: qbittorrent

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: qbittorrent-tls

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
        mountPath: /config/qBittorrent/config

      cache:
        enabled: true
        type: emptyDir
        mountPath: /config/qBittorrent/cache
     
      data:
        enabled: true
        type: emptyDir
        mountPath: /config/qBittorrent/data

      media:
        enabled: true
        existingClaim: media
        path: /media
        mountPath: /data/media