---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/qbittorrent
              tag: 20.04.1

            env:
              QBITTORRENT__PORT: &port 8080

    service:
      main:
        ports:
          http:
            port: *port

    route:
      main:
        hostnames:
          - "qbittorrent.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        existingClaim: qbittorrent-config
        globalMounts:
        - path: /config
      tmp:
        type: emptyDir
      downloads:
        existingClaim: lp-downloads
        globalMounts:
          - path: /data/media/downloads