---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  chartRef:
    kind: OCIRepository
    name: qbittorrent
  interval: 30m

  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/qbittorrent
              tag: 20.04.1

            env:
              QBITTORRENT__PORT: &port 8080

    service:
      main:
        ports:
          http:
            port: *port

    route:
      main:
        hostnames:
          - "qbittorrent.muellner.dev"
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        existingClaim: qbittorrent-config
        globalMounts:
        - path: /config
      tmp:
        type: emptyDir
      downloads:
        existingClaim: lp-downloads
        globalMounts:
          - path: /data/media/downloads