---
apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
stringData:
  HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:Avoc78JRhiU96BkSnIwkma9ORGOcWWEsDeU7oFJk28k=,iv:W/8Ce3dl5cYDUOCZAqVduLpOgrC8T8Yku6P8WfxMmHw=,tag:RYcm9VN8d6/609T4lmC1Fg==,type:str]
  HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:anFxLyMExpnSQ4HSebH9L99MbL6dYUcA87eQil+8Xu0=,iv:1QwenZ2ghgGx7HW3GNsth6Q4tYH+o7FGjhUfcC83w/I=,tag:EdXSzRd7dw3Fy0R9IVxvZA==,type:str]
  HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:HgNJClaKSp73sjUAOlEv+lFYlIheovAaon55itVXU/A=,iv:LwwR/aMqI0ixwvcL4qAx8rhhNz1iXN6ixZT192zzJE4=,tag:s5t82v/10jNng6GeHureZg==,type:str]
  HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:7lJwYHOEh/BvwewFFtHvh43yqGejmYwky6C78FOMbvg=,iv:4a/tlXi8Luo6Bs6etQ5OJNCSHL8aK1inuQnEfGKyDZw=,tag:Z55CSrgjeGeoyNRh38RWYA==,type:str]
  HOMEPAGE_VAR_SABNZBD_KEY: ENC[AES256_GCM,data:Mdi+qqFX2+8lHRSBFiTahxhD+HBg/7aE6FRhFLl/qlU=,iv:utCjsUkEsvHmyI5JkHxZnOvlnn6PRFh8LoBVfT17SO8=,tag:TU34d/6KasNXrjrxpZzu9g==,type:str]
  HOMEPAGE_VAR_SEERR_KEY: ENC[AES256_GCM,data:LGtR8YL5U5GbckUHKPP/m4flfQjVIgBCbDsckR2UwBHgHaIa12RGiW4hlby5qoI7TUZb3QpL+FGIhhsaiincr2Hm7P8=,iv:GNrGVKgBBnprKIaOrYjxF8VWzKVMx9YXgjcVPtHH2lc=,tag:f98nibbdeAq0fqWiXwwyDg==,type:str]
  HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:wSiL+w+j0VFLNUJ9wd0xT4GQfK2VejULdEiaPBs6LzKLuqzHcGOQuq9OfA==,iv:8eDV/LE34rCW9JCDPPTBCc12/oNnbVBp4bb24CgMUtA=,tag:9rnWL5pVAUMv2vjlUwB5zQ==,type:str]
  HOMEPAGE_VAR_PAPERLESS_KEY: ENC[AES256_GCM,data:xekEImvhwYYTMuPwi3APJCeY5xsZBy1A7nFCjhiCWnECqolmapiiVg==,iv:GnGyS2vU8yjkP+0upzZevW+ZVREIhS02Wv4aYhshGdI=,tag:dfOHrq49zniEmTjhTEyrQw==,type:str]
  HOMEPAGE_VAR_KAVITA_USERNAME: ENC[AES256_GCM,data:hdfHq1Q56U8=,iv:CjeSlVnxzbVe49o75anGKF8RF12mGY+ozce71TBYitQ=,tag:GNiuB/YfcAUI1kZkW4xb0Q==,type:str]
  HOMEPAGE_VAR_KAVITA_PASSWORD: ENC[AES256_GCM,data:AUt1s50yTHJYJ/D46oS1mLlBFhQ=,iv:7JOz0ZiJDiz0okcANX7wM6qDHPbzMmzlb34k3Y3Z2WQ=,tag:NpPlGveNVZpMiAR9Nnng8g==,type:str]
  HOMEPAGE_VAR_TANDOOR_KEY: ENC[AES256_GCM,data:7JM90eRNjjR2GWYq57yFxDaabUOwiM2nONlEhGgbxR5z6+5+aXTDSQ==,iv:wx+61iVKpQGaPlRm7bQlW+qRCDe7dYAilHuAROLpvjQ=,tag:2Fi7X0/E1syaJQca6NWugQ==,type:str]
  HOMEPAGE_VAR_HOMEASSISTANT_KEY: ENC[AES256_GCM,data:XC6X5s92fLgHnIZk6LoCYmOwERIy+AhHRAZAx3ymj0ESjH5XCKIwBsul4iyjtWyQyWgTa6OE5xEVFKUz/CtW+VZQavEc2lwp55XVaP1um0H1I53x0c1YtatKPz7LSdczbIUMOTbfKz+z1cfuYfKkq+UMClJeDbnUaJGL23vUD767QsZ29hzyfE0s2KvhSxlQqAILV9SUj7W+XKaV1mRR1YOK5LVW11Wm3JyYnPMSYuuUuasmc8y4,iv:2hWB+EyqL6doOVNFAE8EXO2FhK3F01nk81UyhAKSsVA=,tag:obJ2+f5D9kqF1JLtjYXARw==,type:str]
  HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:12z9wXSn8pA=,iv:/Y8Mwx4pdw1PERUbdmwxftwLAt5Y604E4IleCAeXvhg=,tag:PBQx2GciTZHZR8QTf/6AtA==,type:str]
  HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:TSugo8/jn4a1jR5QStf/pXYHh/3yEOgushngiBop8N8tuVpwGn9EOV6zK4T7Ig==,iv:P1bhSSDQctr4qsnqCdV9twEDxUX2aQ1wfeLFxY4wueg=,tag:0epNcEOwswanOuAX5rfLTw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVjF5dGU1cTRLclV0S254
        M2pJbXRDVGtQdWZ0U1Ewc28xL1UvWGhqODFjCmtBcGlFbDdjeTNxOFVwWXpoV3F3
        aTF3ZDlvTTQ1TFpKc0p1MDh0bWpKQ00KLS0tIHAwR0ExUkpFRWNtRkRSSGt1dnQ3
        ZXFuWEVoWllydFJ1UUtyUVgyOU0zTmMKZyd5ZImFUPa8fWch8uQSVhbO8MUUCSqB
        yPrgeYzABrT+whqeopfdO/0au1KDbRetEW7km4xINEtkVGpjQDcwiQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-02T21:35:14Z"
  mac: ENC[AES256_GCM,data:vC+cI/PV0Q0MLm3MOwmDJihRzNqG9zKBRsQyCqAzcPDWCMVsFBCsqAkcwxWRhbZrPNTbWQhxo8NI5XFJtaGaHrD/HhE8mLrujiAI5MQBdvUycerteo3ZAhHxInTIzcGB8tV3+9F1f4JQ2owIq1RHmt7gSfCKbJgSD9pQRa+r4S0=,iv:kYwLPzeScoJdU8jHS/l8NrqrMPXgARgZ7G/L5y4IP40=,tag:IDMvx86Hn5gBiPBeTRwugQ==,type:str]
  version: 3.13.3
