- platform: bayesian
  name: Home
  device_class: presence
  prior: 0.6
  probability_threshold: 0.9
  observations:
    - platform: template
      value_template: >
        {{is_state('device_tracker.mc_iphone','home') and ((as_timestamp(now()) - as_timestamp(states.device_tracker.mc_iphone.last_changed)) > 300)}}
      prob_given_true: 0.99
      prob_given_false: 0.05