- binary_sensor:
  - name: "Washing Machine (avg)"
    state: >
      {{ states('sensor.washer_power_over_last_5_minutes')|float > 10 }}
- binary_sensor:
  - name: "Washing Machine (direct)"
    delay_off:
      minutes: 5
    state: >
      {{ states('sensor.smartplug_washer_power')|float > 10 }}