apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: truecharts-sonarr
spec:
  releaseName: truecharts-sonarr
  chart:
    spec:
      chart: sonarr
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      version: ">=11.0.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    env:
      - name: TZ
        value: Europe/Vienna
    
    # persistence:

    # ingress:

    # addons: