apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  labels:
    app.kubernetes.io/name: data
    app.kubernetes.io/instance: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi