apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &release calibre
spec:
  releaseName: *release
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      calibre:
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/calibre
              tag: 7.24.0
            env:
              TZ: Europe/Vienna

    service:
      app:
        controller: calibre
        ports:
          http:
            port: 8080
      content-server:
        controller: calibre
        ports:
          http:
            port: 8081

    ingress:
      app:
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "calibre.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: calibre-tls

    persistence:
      config:
        existingClaim: calibre-config
        globalMounts:
          - path: /config
      media:
        existingClaim: media
        globalMounts: 
          - path: /data/media