apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &release prowlarr
spec:
  releaseName: *release
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/prowlarr-develop
      tag: 1.0.0.2181

    env:
      TZ: Europe/Vienna
    
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config
        mountPath: /config

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "prowlarr.media.local"
            paths:
              - path: /
                pathType: Prefix
                service: 
                  name: *release
                  port: 9117
        tls:
          - hosts:
              - *host