apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &release prowlarr
spec:
  releaseName: *release
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/prowlarr-develop
      tag: 1.0.0.2181

    env:
      TZ: Europe/Vienna
      PROWLARR__INSTANCE_NAME: Prowlarr
      PROWLARR__PORT: &port 9696
      PROWLARR__LOG_LEVEL: info
      PROWLARR__ANALYTICS_ENABLED: "False"
      # PROWLARR__API_KEY:
      #   valueFrom:
      #     secretKeyRef:
      #       name: prowlarr-secrets
      #       key: api_key

    hostname: prowlarr

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "prowlarr.media.local"
            paths:
              - path: /
                pathType: Prefix
                service: 
                  name: *release
                  port: 9117
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config
        mountPath: /config