apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: home-assistant
  app.kubernetes.io/instance: home-assistant