---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2024.12.2@sha256:b38999b991695f6595549155bca2c5c74729041b06c25b0407102d733cc86f66

    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: homeassistant-tls

    persistence:
      configuration-file:
        enabled: true
        type: configMap
        name: homeassistant-config
        mountPath: /config/configuration.yaml
        subPath: configuration.yaml
      config:
        enabled: true
        existingClaim: homeassistant-config
        mountPath: /config
      binary-sensor-file:
        enabled: true
        type: configMap
        name: homeassistant-binary-sensor
        mountPath: /config/binary_sensor.yaml
        subPath: binary_sensor.yaml

    securityContext:
      privileged: true
    resources:
      limits:
        akri.sh/conbee-gateway: "1"
      requests:
        akri.sh/conbee-gateway: "1"
