---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controller:
      type: statefulset

    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2023.1.7

    envFrom:
      - configMapRef:
          name: homeassistant-config

    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: homeassistant-tls

    persistence:
      config:
        enabled: true
        existingClaim: homeassistant-config
        mountPath: /config