---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2025.2.4@sha256:dae013e0bd935bf8dc500adef771604a3fd03dc5f2ca13b9566f51a094e3f8bf

    service:
      main:
        controller: main
        ports:
          http:
            port: 8123

    ingress:
      main:
        className: nginx
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
            - path: /
              service:
                identifier: main
                port: http

    persistence:
      configuration-file:
        type: configMap
        name: homeassistant-config
        globalMounts:
        - path: /config/configuration.yaml
          subPath: configuration.yaml
      config:
        existingClaim: homeassistant-config
        globalMounts:
        - path: /config
      binary-sensor-file:
        type: configMap
        name: homeassistant-binary-sensor
        globalMounts:
        - path: /config/binary_sensor.yaml
          subPath: binary_sensor.yaml
      sensor-file:
        type: configMap
        name: homeassistant-sensor
        globalMounts:
        - path: /config/sensor.yaml
          subPath: sensor.yaml
      template-file:
        type: configMap
        name: homeassistant-template
        globalMounts:
        - path: /config/template.yaml
          subPath: template.yaml
