apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - helmrelease.yaml
  - pvc.yaml
configMapGenerator:
- name: homeassistant-config
  files:
  - ./config/configuration.yaml
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  app.kubernetes.io/name: homeassistant
  app.kubernetes.io/instance: homeassistant