apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - helmrelease.yaml
  - pvc.yaml
  - config.yaml
commonLabels:
  app.kubernetes.io/name: homeassistant
  app.kubernetes.io/instance: homeassistant