apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: homeassistant-secret
    namespace: home-automation
data:
    SECRET_INTERNAL_URL: https://"hass.${SECRET_DOMAIN}"
    SECRET_EXTERNAL_URL: https://"hass.${SECRET_DOMAIN}"
    SECRET_TRUSTED_PROXIES_1: 10.0.0.0/8