---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-coredns
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/kube-system/coredns/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true