---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: akri
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: akri
      version: 0.9.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: akri
        namespace: flux-system
  values:
    kubernetesDistro: k3s

    udev:
      discovery:
        enabled: true
      configuration:
        enabled: true
        discoveryDetails:
          udevRules:
            - 'SUBSYSTEM=="usb", ATTR{product}=="ConBee II"'