---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: akri
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: akri
      version: 0.13.8
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: akri
        namespace: flux-system
  values:
    webhookConfiguration:
      enabled: false
    kubernetesDistro: k3s

    udev:
      discovery:
        enabled: true