apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - helmrelease.yaml
  - config/zigbee-gateway.yaml
commonLabels:
  app.kubernetes.io/name: akri
  app.kubernetes.io/instance: akri