---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cilium
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/network/cilium/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cilium-config
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/network/cilium/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  dependsOn:
    - name: cluster-apps-cilium