---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      mosquitto:
        containers:
          app:
            image:
              repository: eclipse-mosquitto
              tag: 2.0.20

    service:
      app:
        controller: mosquitto
        ports:
          http:
            port: 1883

    ingress:
      app:
        className: "nginx"
        hosts:
          - host: &host "mosquitto.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      configuration-file:
        type: configMap
        name: mosquitto-conf
        globalMounts:
          - path: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
      password-file:
        type: secret
        name: mosquitto-passwd
        globalMounts:
          - path: /mosquitto/config/passwords.txt
            subPath: passwords.txt
      config:
        existingClaim: mosquitto-config
        globalMounts:
          - path: /mosquitto/data
            subPath: data
          - path: /mosquitto/log
            subPath: log