apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    HASS_LATITUDE: ENC[AES256_GCM,data:qM9tXyfi9/Drxuw/A8UhLEs=,iv:/6GAiM2hLjKNbX25xLaV7ZsGjCn0O2+p374hcN+30fo=,tag:axqh4c9HjuMHzYHiTIHMLA==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:AtCg17ijsI2rajV1hSO0dnGN,iv:tvrpgLnIYI3cVxRh7jDznm+JIejX0YSO24mp4v2s+5k=,tag:MMJfbjJRKwzjdzj/5D+naA==,type:str]
    HASS_REMOTE_URL: ENC[AES256_GCM,data:RfcjDgO9XRVawUMdsxSqbjxj5VHlw8nnWWalK6IdKNrCBdWxUBk/ikkKvRMZsb/qsMOOcceL,iv:H7lwCFRHRp6BPtFIaQAQlQCrSbIwRS1Vs457fGrfpj0=,tag:chdyw7iehJtaMSZ3QbA4tA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWTBUMFRTTng0RmFMWWMr
            VThuTTQ2Sk4xUDRiRlZ5d0FidmRPek9pOFVBCkFudTJoS2ZxVmhtdXl3WWhZNmJv
            RE1TVWN0K1dFNGRHQWV3T09nWS9ZVzQKLS0tIDRuVHBoVWlwbFhEUTdUWVN0WTFk
            QktoazU3QTJoUlh1S0hZRWVYZC9GMWcKNibtK0vUFav0dhky+5Rxxoe0sgCrm8dM
            JLMy/DCNo6ySErAzbrbLv7L9Z9+7etFcXlm6Gro7MJOqm77QXes5hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-17T21:37:01Z"
    mac: ENC[AES256_GCM,data:uqF8WjqlM9MhZAIVkjlDZ9OIDwHsV4+u3XPZ2tPG7bttxfRIXzV00Usvgbihh3/5KJcC0FbBZ3UjQ2APyqXrLmzAgRV+fq1/i+7+v0vjFR4lp8tH+RuebYTyXo1pnOTyjw30UEUZzeSPjpWiyp5fnacLK9NBS6UjkR8ZGjr49bg=,iv:IjNb3qbVpM5ecqB4PFqxyfwpcKdaQ1VwCnV/piy21YY=,tag:baDP+nK5qK8BMo3G38qfjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
