---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  LB_RANGE: 192.168.10.220/29
  SVC_K8S_GATEWAY_ADDR:  192.168.10.220
  SVC_INGRESS_ADDR: 192.168.10.221