---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    operator:
      replicas: 1

    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
        ingress:
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
          hosts:
            - &host "hubble.${SECRET_DOMAIN}"
          tls:
            - hosts:
                - *host
              secretName: hubble-tls
      metrics:
        enabled:
        - dns:query