apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &release sonarr
spec:
  releaseName: *release
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/sonarr
              tag: 4.0.16
            env:
              TZ: Europe/Vienna
              SONARR__INSTANCE_NAME: Sonarr
              SONARR__PORT: &port 8989
              SONARR__APPLICATION_URL: &host "sonarr.${SECRET_DOMAIN}"
              SONARR__LOG_LEVEL: info

    service:
      main:
        controller: main
        ports:
          http:
            port: *port

    ingress:
      main:
        className: "nginx"
        hosts:
          - host: *host
            paths:
            - path: /
              service:
                identifier: main
                port: http

    persistence:
      config:
        existingClaim: sonarr-config
        globalMounts:
        - path: /config
      downloads:
        existingClaim: lp-downloads
        globalMounts:
          - path: /data/media/downloads
      shows:
        existingClaim: pvc-shows
        globalMounts:
          - path: /data/media/shows
