apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &release sonarr
spec:
  releaseName: *release
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.2.1223@sha256:cfbc8e75d28270e1d88ead0160eead8f77a383ee05df2a46e3ce7022e3bd9ea8

    env:
      TZ: Europe/Vienna
      SONARR__INSTANCE_NAME: Sonarr
      SONARR__PORT: &port 8989
      SONARR__APPLICATION_URL: &host "sonarr.${SECRET_DOMAIN}"
      SONARR__LOG_LEVEL: info
      # SONARR__API_KEY:
      #   valueFrom:
      #     secretKeyRef:
      #       name: sonarr-secrets
      #       key: api_key

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: sonarr-tls

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
        mountPath: /config
      media:
        enabled: true
        existingClaim: media
        path: /media
        mountPath: /data/media