---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
spec:
  interval: 30m
  chart:
    spec:
      chart: ./deploy/chart/local-path-provisioner
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
        namespace: system
      interval: 30m
  values:
    
