---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: system
spec:
  interval: 30m
  chart:
    spec:
      chart: ./local-path-provisioner
      # version: 0.0.25-dev
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
        namespace: flux-system
      interval: 30m
  values:
    
