---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-sonarr
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/media/sonarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true