---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: zigbee2mqtt
      version: 2.0.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: zigbee2mqtt
        namespace: flux-system
  values:
    image:
      repository: koenkk/zigbee2mqtt
      tag: 2.0.0
    statefulset:
      resources:
        requests:
          memory: 600Mi
          cpu: 200m
          akri.sh/zigbee-gateway: "1"
        limits:
          memory: 600Mi
          cpu: 200m
          akri.sh/zigbee-gateway: "1"
