---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      zigbee2mqtt:
        type: statefulset
        containers:
          app:
            image:
              repository: koenkk/zigbee2mqtt
              tag: 2.0.0
            resources:
              requests:
                memory: 600Mi
                cpu: 200m
                akri.sh/zigbee-gateway: "1"
              limits:
                memory: 600Mi
                cpu: 200m
                akri.sh/zigbee-gateway: "1"
            env:
              # https://www.zigbee2mqtt.io/guide/configuration/#environment-variables
              ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: true
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto:1883
              ZIGBEE2MQTT_CONFIG_MQTT_USER: mqtt
              ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: test
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: /dev/ttyUSB0
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: zstack # https://www.zigbee2mqtt.io/guide/adapters/zstack.html
              ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED: true
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED: true

    service:
      app:
        controller: zigbee2mqtt
        ports:
          http:
            port: 8080

    ingress:
      app:
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "zigbee2mqtt.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: zigbee2mqtt-tls

    persistence:
      config:
        existingClaim: zigbee2mqtt-config
        globalMounts:
          - path: /app/data