---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      zigbee2mqtt:
        type: statefulset
        containers:
          app:
            image:
              repository: koenkk/zigbee2mqtt
              tag: 2.0.0
            resources:
              requests:
                memory: 600Mi
                cpu: 200m
                akri.sh/zigbee-gateway: "1"
              limits:
                memory: 600Mi
                cpu: 200m
                akri.sh/zigbee-gateway: "1"

    service:
      app:
        controller: zigbee2mqtt
        ports:
          http:
            port: 8080

    ingress:
      app:
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "zigbee2mqtt.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: zigbee2mqtt-tls

    persistence:
      config:
        existingClaim: zigbee2mqtt-config
        globalMounts:
          - path: /app/data
      configuration-file:
        type: configMap
        name: zigbee2mqtt-config
        globalMounts:
          - path: /app/data/configuration.yaml
            subPath: configuration.yaml