---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
spec:
  chartRef:
    kind: OCIRepository
    name: sabnzbd
  interval: 30m

  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/sabnzbd
              tag: 4.5.5

            env:
              SABNZBD__PORT: &port 80
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.media,
                sabnzbd.media.svc,
                sabnzbd.media.svc.cluster,
                sabnzbd.media.svc.cluster.local,
                sab.muellner.dev,
                sabnzbd.muellner.dev

    service:
      main:
        ports:
          http:
            port: *port

    route:
      main:
        hostnames:
          - "sabnzbd.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        existingClaim: sabnzbd-config
        globalMounts:
        - path: /config
      tmp:
        type: emptyDir
      downloads:
        existingClaim: lp-downloads
        globalMounts:
          - path: /data/media/downloads