---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/sabnzbd
              tag: 4.5.5

            env:
              SABNZBD__PORT: &port 80
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.media,
                sabnzbd.media.svc,
                sabnzbd.media.svc.cluster,
                sabnzbd.media.svc.cluster.local,
                sab.muellner.dev,
                sabnzbd.muellner.dev

    service:
      main:
        controller: main
        ports:
          http:
            port: *port

    ingress:
      main:
        className: nginx
        hosts:
          - host: &host "sabnzbd.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http

    persistence:
      config:
        existingClaim: sabnzbd-config
        globalMounts:
        - path: /config
      tmp:
        type: emptyDir
      downloads:
        existingClaim: lp-downloads
        globalMounts:
          - path: /data/media/downloads