apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=docker image=rancher/system-upgrade-controller
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.11.0/crd.yaml
  - https://github.com/rancher/system-upgrade-controller?ref=v0.13.3
images:
  - name: rancher/system-upgrade-controller
    newTag: v0.13.3@sha256:9407a0197249519521d92489b6590dfd1524ef3169ca64cae626bbd2254045a6
patchesStrategicMerge:
  - |
    $patch: delete
    apiVersion: v1
    kind: Namespace
    metadata:
      name: system-upgrade
labels:
  - pairs:
      app.kubernetes.io/name: system-upgrade-controller
      app.kubernetes.io/instance: system-upgrade-controller
    includeSelectors: true