apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:+MSzXq7vZy+X4q/z,iv:YOh6Cx/r9Cjq1Jleoa9AYGJaYDL8iuo5AjBnNunrhCA=,tag:lVWss2PLF8hq39qDttPo/A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:a+soltkxSkCvKjS2W+qur2uQSGlpKZIg,iv:IO/Bt4zf+GED6CY2tFbw2u6K59Sg/5sD2P/X4oCl7aA=,tag:q6hg3hbY3rtPvXdxBt+B2Q==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:1ImCXSGzPGWuS+2wLvbJmedej/JOJr0wncrxdzQXbYr2ctGdG8J9zw==,iv:8fnALClFaie7eiVMnDB+XGdE+mxIq9L1/N8K9v7RqMU=,tag:tgocxuK4KLb+CcEXDtzg6g==,type:str]
    HASS_LATITUDE: ENC[AES256_GCM,data:Z/irEaGjl5HlzMpeSHEr9AQ=,iv:hnZGYNn2Uqfna8Fvzhzr/WpOyyD0yxEkEGHpFt2z2bc=,tag:oQXSexJW54W2zJYxBgKwyg==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:a++hDP/l76mp6UuGH+vVrDzJ,iv:iKpG9xr9Gh7v5TCy8dR4Sg2SFrL7fWAV5iqX//LLG7I=,tag:9nIBNV+8WkmqHdN4CiMFYw==,type:str]
    HASS_REMOTE_URL: ENC[AES256_GCM,data:3AQfQcUxctnBe/fgnL3uqXyDYhPDhqxnxGrssTiHhtq/9lebhqLy/Ohe/8Kn4fLxpeHwswqy,iv:7G0p01gFX0cYNWG1LK+DyL9+ufvt3Tj9UlxRieVBqOg=,tag:6VXCIKzeJqrEBpw378RwPw==,type:str]
sops:
    age:
        - recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodXZEMzBLSTNGTkwrT2hj
            S0o3ZW8zcm5JWlhIQ3g0dG5lbXlGWWZmcEc0Cm51MHRYRFFxM2Y3ZVRoUnRKSTVL
            YXhyL0xSNFRja3VUbCtnNHNlSHg4UXMKLS0tIDY1cVIvQWtaTHFURVJ0MDBXS01q
            R0EvLzhMZ1VjV3NZRnRhakZwaGFjc2sKTFtGQoVdjyMk801/XhjA2UkPa0MdrAcm
            id5o03s4MqiBZBz5s+FtBRk6mNC3TsmgSmXak1Y+X/J6VP5A8IdzpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T20:08:30Z"
    mac: ENC[AES256_GCM,data:+xZ9yX0Kjx9HG6SXImJekiM5JK8ps/3wvPspCxURLqxIMZ1vzzSD1G7eDh/JUWVvsGae8/U2ja7GOU00dLdyl0WWRtUKhBdBbz2GIoJG+qUGWPNkwo7D7Y/zzmYsaibjT60MJ7cZ/iaOKcaIu8UZGlqCDdK5/9tKjDPWtLSt500=,iv:ftYgfQOEvOFL6t49nqKJxspRg9A3lMr/TSxnuyOOtFM=,tag:5dk7F4gd8liooGShrPkDug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
