---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kaniop.rs/kanidmpersonaccount_v1beta1.json
apiVersion: kaniop.rs/v1beta1
kind: KanidmPersonAccount
metadata:
  name: chris
spec:
  kanidmRef:
    name: kanidm
  personAttributes:
    displayname: Christoph Muellner
