---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: network
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: metallb
    
  values:
    image:
      repository: quay.io/oriedge/k8s_gateway
      tag: v0.3.2
      pullPolicy: IfNotPresent

    args: ["-conf", "/etc/coredns/Corefile"]

    configMaps:
      config:
        enabled: true
        data:
          Corefile: |
            .:1053 {
              errors
              log
              cache

              k8s_gateway "${SECRET_DOMAIN}" {
                apex  k8s-gateway.network
                resources Ingress Service
                ttl 300
              }

              forward . tls://94.140.14.14 tls://94.140.15.15 {
                tls_servername dns.adguard.com
              }

              forward . 1.1.1.1 1.0.0.1 {
                tls_servername cloudflare-dns.com
              }

              prometheus :9153
            }
    
    serviceAccount:
      create: true
      name: k8s-gateway

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: "${SVC_K8S_GATEWAY_ADDR}"
        ports:
          http:
            enabled: false
          dns:
            enabled: true
            port: 53
            targetPort: 1053
            protocol: UDP

    persistence:
      config:
        enabled: true
        type: configMap
        name: k8s-gateway-config
        mountPath: /etc/coredns
        readOnly: true

    probes:
      readiness:
        custom: true
        spec:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
      liveness:
        custom: true
        spec:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
      startup:
        custom: true
        spec:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP

    resources: {}
