---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: network
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
    
  values:
    image:
      repository: quay.io/oriedge/k8s_gateway
      tag: v0.4.0@sha256:7bdbd447c0244b8f89de9cd6f4826ed0ac66c9406fac3a4ac80081020c251c6b
      pullPolicy: IfNotPresent

    args: ["-conf", "/etc/coredns/Corefile"]

    configMaps:
      config:
        enabled: true
        data:
          Corefile: |
            .:1053 {
              errors
              log
              health {
                lameduck 5s
              }
              ready
              cache
              prometheus :9153

              k8s_gateway "${SECRET_DOMAIN}" {
                apex  k8s-gateway.network
                resources Ingress Service
                ttl 300
              }

              forward . 1.1.1.1 1.0.0.1 {
                tls_servername cloudflare-dns.com
              }
            }
    
    serviceAccount:
      create: true
      name: k8s-gateway

    service:
      main:
        type: ClusterIP
        ports:
          http:
            enabled: false
          dns:
            enabled: true
            port: 53
            targetPort: 1053
            protocol: UDP

    persistence:
      config:
        enabled: true
        type: configMap
        name: k8s-gateway-config
        mountPath: /etc/coredns
        readOnly: true

    probes:
      readiness:
        custom: true
        spec:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
      liveness:
        custom: true
        spec:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
      startup:
        custom: true
        spec:
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP

    resources: {}
