---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cilium-config
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/kube-system/cilium/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
