apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  custom.server: |
    dns://.:1053 {
      hosts {
        192.168.10.65 jellyfin.muellner.dev
        192.168.10.65 prowlarr.muellner.dev
        192.168.10.65 qbittorrent.muellner.dev
        192.168.10.65 radarr.muellner.dev
        192.168.10.65 sonarr.muellner.dev
        fallthrough
      }
      forward . tls://94.140.14.14 dns://1.1.1.1 dns://1.0.0.1 {
        tls_servername dns.adguard.com
      }
      errors
      cache
      log
    }