apiVersion: v1
kind: Service
metadata:
  name: coredns-custom
  namespace: kube-system
spec:
  type: NodePort
  selector:
    k8s-app: kube-dns
  ports:
    - name: coredns-custom-udp
      protocol: UDP
      port: 53
      targetPort: 1053
    - name: coredns-custom-tcp
      protocol: TCP
      port: 53
      targetPort: 1053