---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-qbittorrent
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/media/qbittorrent/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  dependsOn:
    - name: apps-pod-gateway-media