---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: mediaserver
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.4.5

    podAnnotations:
      setGateway: "true"

    env:
      UMASK: "022"
      QBITTORRENT__PORT: &port 8080
      QBITTORRENT__USE_PROFILE: "true"

    hostname: qbittorrent

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "qbittorrent.media.local"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config
        mountPath: /config/qBittorrent/config

      cache:
        enabled: true
        type: emptyDir
        mountPath: /config/qBittorrent/cache

      media:
        enabled: true
        existingClaim: media
        mountPath: /downloads