---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-csi-driver-smb
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/system/csi-driver-smb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
