---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "domain-tls"
  namespace: network
spec:
  secretName: "domain-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
