---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: network
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      config:
        use-forwarded-headers: "true"
        force-ssl-redirect: "true" # https://kubernetes.github.io/ingress-nginx/user-guide/tls/
        proxy-body-size: 0 # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#proxy-body-size
      
      service:
        enabled: true
        annotations:
          io.cilium/lb-ipam-ips: "${SVC_INGRESS_ADDR}"

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: kube-system
          namespaceSelector:
            any: true

      extraArgs:
        default-ssl-certificate: "network/muellner-dev-tls"