---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: events-pull-secret
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:HYKlqjWgoSCiOhJ/f7ArRLYHnZPzygogrb+fd1POze3GhMZ52bK2IdSYm1qKGf9kzjjz9cxAwEwwRWpAYJpRbpv3sLybqdeQuPLSg8SpDlXHP3rKt7E4IhTYxrbYtM8rafEWdRNwtayoFg==,iv:IKQFEzmpE3hQRMeNDmaI7cJ5vSnrR4FNBtVRPHY9Rcw=,tag:UioApADC0pKowHfZr+OYxg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQVIzTlh6SkdzODJuZWtq
        NyswZDkxclVEcEppdGJxRUpaV0RZSVVDYmh3Clk4Zzk5bysyODk1Y3hrbFZ3aFFz
        eDhaaXY0RnlNbzh1c1VOSUFkeVR3cjgKLS0tIFQweXJTU2pIVkJJMFN5VDQwV0dq
        SmNFdVRBWkovUlhleE1BaU14NTFTR28Ky3F6dQ3NklQK3x5uPYg+OqITvL4RFVea
        zYfHNFN+lj0kqMNV40bnpF/SJlYPutSHnltp2J4nqH6v3zI+r16eUg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17ja9fh9emzdtgzy6as2t92x20sjpxp4xt6tvuyu7n2nr2ctrv3aq4ul5tl
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-19T12:23:16Z"
  mac: ENC[AES256_GCM,data:wIFo6TymzuJr88QlgA4O7lTAGBb6YKotLGIKgslOaiorRawLSBccDUgNSP6tcQZMmUnfhyBNapwwcneRQDsPkrPwoFeAuBNEGspvhYN6vxN5DIfJCR7+F8YmNUb+S1Ls4m71M59+aUvKamLyYUpFaE4DCGvqYSqLE7Uen8Sp4uY=,iv:vln4pK/52HrDYUueQjjcW6TggbtCUKnTXUdNBOX0/fo=,tag:4n7/zNkbwdw97dfNN0Iznw==,type:str]
  version: 3.13.1
