---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.14.3
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 30m
  values:
    cluster:
      id: 0
      name: "default"

    operator:
      replicas: 1

    containerRuntime:
      integration: containerd
      socketPath: "/var/run/k3s/containerd/containerd.sock"
    
    policyEnforcementMode: "never"

    ipam:
      operator:
        clusterPoolIPv4PodCIDRList: "10.42.0.0/16"

    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
      metrics:
        enabled:
        - dns:query