---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.13.2
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 30m
  values:
    cluster:
      id: 0
      name: "default"

    encryption:
      nodeEncryption: false

    ipam:
      mode: "cluster-pool"
      clusterPoolIPv4PodCIDRList:
        - "${LB_RANGE}"

    kubeProxyReplacement: "disabled"

    operator:
      replicas: 1

    serviceAccounts:
      cilium:
        name: "cilium"
      cilium-operator:
        name: "cilium-operator"

    tunnel: "vxlan"