apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  chartRef:
    kind: OCIRepository
    name: immich
  interval: 1h
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      server:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          enableServiceLinks: false

        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.4.1
            env:
              IMMICH_MEDIA_LOCATION: &mediaLocation /usr/src/app/upload
              DB_DATABASE_NAME: &databaseName "immich"
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-secret
                    key: POSTGRES_USER
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-secret
                    key: POSTGRES_PASSWORD
            envFrom:
              - configMapRef:
                  name: immich-configmap

      machine-learning:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          enableServiceLinks: false

        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v2.4.1
            env:
              MPLCONFIGDIR: "/cache/matplotlib"
              IMMICH_MEDIA_LOCATION: *mediaLocation
              DB_DATABASE_NAME: &databaseName "immich"
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-secret
                    key: POSTGRES_USER
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-secret
                    key: POSTGRES_PASSWORD
            envFrom:
              - configMapRef:
                  name: immich-configmap

      valkey:
        containers:
          app:
            image:
              repository: docker.io/valkey/valkey
              tag: 8-bookworm

      database:
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/postgres
              tag: 17-vectorchord0.4.3
            env:
              POSTGRES_USER:
                    valueFrom:
                      secretKeyRef:
                        name: immich-secret
                        key: POSTGRES_USER
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-secret
                    key: POSTGRES_PASSWORD
              POSTGRES_DB: *databaseName
              POSTGRES_INITDB_ARGS: '--data-checksums'

    service:
      server:
        controller: server
        ports:
          http:
            port: &port 2283
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: 3003
      valkey:
        controller: valkey
        ports:
          http:
            port: 6379
      database:
        controller: database
        ports:
          http:
            port: 5432

    route:
      main:
        hostnames:
          - "immich.muellner.dev"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
            - identifier: server
              port: *port

    persistence:
      matplotlib:
        type: emptyDir
        advancedMounts:
          server:
            main:
              - path: /config/matplotlib

      library:
        type: persistentVolumeClaim
        existingClaim: pvc-photos
        advancedMounts:
          server:
            main:
            - path: *mediaLocation
              subPath: immich
            - path: /data/camera
              subPath: camera
            - path: /data/phone
              subPath: phone

      cache:
        type: persistentVolumeClaim
        existingClaim: immich-machine-learning-cache
        globalMounts:
          - path: /cache
            subPath: cache
          - path: /.cache
            subPath: dotCache

      tmpfs:
        type: emptyDir
        advancedMounts:
          server:
            main:
              - path: /usr/src/app/.reverse-geocoding-dump
                subPath: geocoding
              - path: /usr/src/app/.transformers_cache
                subPath: transformers

      database:
        type: persistentVolumeClaim
        existingClaim: immich-database
        advancedMounts:
          database:
            app:
            - path: /var/lib/postgresql/data