apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-machine-learning-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi