---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-zigbee2mqtt
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/home-automation/zigbee2mqtt/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
