---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-documents
  namespace: selfhosted
spec:
  volumeName: pv-documents
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
