apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server
  namespace: system-upgrade
spec:
  # renovate: datasource=github-releases depName=rancher/rke2
  version: "v1.31.3+rke2r1"
  concurrency: 1
  nodeSelector:
    matchExpressions:
      #  - {key: rke2-upgrade, operator: Exists}
      - {key: rke2-upgrade, operator: NotIn, values: ["disabled", "false"]}
      - {key: node-role.kubernetes.io/control-plane, operator: In, values: ["true"]}
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"
  serviceAccountName: system-upgrade
  cordon: true
#  drain:
#    force: true
  upgrade:
    image: rancher/rke2-upgrade