---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-prowlarr
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/media/prowlarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true