---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-pod-gateway-media
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/vpn/pod-gateway/media
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  dependsOn:
    - name: cluster-apps-cert-manager
