---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-pod-gateway-media
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/vpn/pod-gateway/media
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: cluster-apps-cert-manager