---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
      - kind: Secret
        name: cluster-secrets-common
      - kind: ConfigMap
        name: cluster-settings
      - kind: ConfigMap
        name: cluster-settings-common
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
          namespace: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
          postBuild:
            substituteFrom:
              - kind: Secret
                name: cluster-secrets
              - kind: Secret
                name: cluster-secrets-common
              - kind: ConfigMap
                name: cluster-settings
              - kind: ConfigMap
                name: cluster-settings-common
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
