---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ingress-nginx
  namespace: flux-system
spec:
  path: ./apps/network/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: ingress-nginx
      namespace: network
  interval: 30m
  retryInterval: 1m
  timeout: 3m
