---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ingress-nginx
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/network/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops
  wait: true
  dependsOn:
  - name: cluster-apps-cert-manager
  - name: cluster-apps-cert-manager-issuers
